### ISSUE TITLE
Stop lang_update in case of lexrep double with conflicting labels

### ISSUE THREAD

**Issue by ISC-NLeclercq** [intersystems/iknow#119]
During lang_update processing a lexrep double with conflicting labels currently only results in a notification. Instead it should stop the language compilation, so the conflict can be resolved.

Example:
;;letošními;;CSAdj;CSAdjInstrPl;CSBeginTime;
;;letošními;;CSVerb;

Message:
conflicting double: leto┼ín├¡mi Labels= CSVerb; ***conflicts with*** CSAdj;CSAdjInstrPl;CSBeginTime;

Result:
Successfully installed iknowpy

Trace output:
LexrepIdentified:letošními:CSVerb;

**Comment by ISC-SDE** [comment]
Compilation stops with an error message now: "Conflicting double in lexrep statemachine building..." with details about the conflict.
Thanks!
