### ISSUE TITLE
Japanese model consumes inordinate memory when compiled by Clang

### ISSUE THREAD

**Issue by woodfinisc** [intersystems/iknow#12]
Compiling an optimized version of the Japanese model on Mac with clang consumes just about all the memory my system can give it (32GB).

I've tried to reduce this down to a test case I could report to the clang team but without success to date.

I think we need to adjust the Makefile for the Japanese model to not attempt to optimize on any platform (it causes less severe but notable problems on Linux with gcc as well, IIRC). -O0

**Comment by JosDenysGitHub** [comment]
It also takes a very long time compiling with VS on Windows, and I remember it failed on some Linux machine, we had to switch off the optimizer.
We should measure the perlormance loss, but I don't think that will be much, it's state machine data.

**Comment by JosDenysGitHub** [comment]
Switching off the optimizer for Japanese language model building solves this problem, there's almost no runtime penalty, this is all state-machine data.

**Comment by woodfinisc** [comment]
Excellent!
