### ISSUE TITLE
Python API uses opaque integer values for attribute types

### ISSUE THREAD

**Issue by woodfinisc** [intersystems/iknow#15]
'sent_attributes': [{'entity_ref': 10,
                                     'marker_': 'not',
                                     'offset_start_': 64,
                                     'offset_stop_': 67,
                                     **'type_': 1,**
                                     'unit2_': '',
                                     'unit_': '',
                                     'value2_': '',
                                     'value_': ''}]}]}

These should be human-readable strings.

**Comment by bdeboe** [comment]
There's a $$$IKATTTYPENAME() macro that maps these in the IRIS codebase in %IKInclude.inc, but @JosDenysGitHub will likely be able to point you to the C/C++ equivalent in this repo

**Comment by adang1345** [comment]
Addressed with 377bc6ff00b5dc969eb30f71d9baead7f4381cd0
