### ISSUE TITLE
Japanese: support for measurement attributes

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#150]
Support for measurement attributes in the Japanese language model.

**Comment by makorin0315** [comment]
Branch multi_valunit_parameters has been successfully tested and merged.

**Comment by makorin0315** [comment]
@Rei-hub - Measurement attributes are now supported in Japanese. We'd appreciate your evaluation and feedback. Thanks as always for your cooperation.

**Comment by Rei-hub** [comment]
I'm really happy to hear the great news and appreciate the improvement. 
I have updated to the new version immediately, I'll try it and give feedback to you soon.
