### ISSUE TITLE
Japanese: make percentage expressions (% and 割分厘毛) Measurement 

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#166]
In the latest Measurement implementation in the Japanese language model, percentage is not considered Measurement. It has been brought up in discussions with Dr. Torikai and Dr. Noguchi (@Rei_hub) that percentages are often in the clinical test results, and thus it would be preferable to make them Measurement attributes.

In Japanese, there are 2 types of percentage expressions.

- same as western languages, i.e., "25.92%", "32%"
- expressions often used in written Japanese language, i.e., "２割5分9厘2毛", "3割2分"

1. In case of western-style percentage, the number ("25.92" and "32" in above examples) will be the value and "%" will be the unit, the same way percentages are implemented in English.
2. In case of the Japanese-style (割分厘毛) expression, the entire expression ("２割5分9厘2毛" and "3割2分") should have the Measurement attribute, but without value or unit properties.

**Comment by Rei-hub** [comment]
Thank you for raise an issue about our discussion. 
As we discussed, percentage expressions should be detected as Measurement especially in the medical field.
Of course, in other fields except for the medical field, they may be noises; however, Making the function optional or removing unnecessary attributes by post-processing resolves the problem.
If you have any concerns or need further discussion, let me know. Thank you for your consideration.

**Comment by makorin0315** [comment]
@Rei-hub: As of the latest implementation, Numbers followed by the percent sign "%" are now Measurements, with number being "Value" and "%" being "Unit". In addition, expressions such as "２割5分9厘2毛" and "3割2分" now have Measurement attributes, although they do not have Value/Unit properties. Please note that the work for issue #170 is still continuing. Hoping to close it in the near future.
