### ISSUE TITLE
Handle the JSON for Modern C++ dependency better in build

### ISSUE THREAD

**Issue by isc-adang** [intersystems/iknow#177]
A dependency on JSON for Modern C++ was added in a25e12a048da96a6dad20f12ab9b1220d5fc3b03. This breaks the autoupdater (see failed run https://github.com/intersystems/iknow/actions/runs/1309968599) because the dependency was added to the autoupdate section of `actions/dependencies.sh`, while the autoupdater was not changed to know how to check for updates for this dependency.

In addition, the current way that this dependency is installed at build time is not the most efficient. Doing a `git pull` and `git checkout` is more expensive than downloading from the GitHub releases section directly, and build caching can be added to speed things up further.

My proposal is to update the handling of the JSON for Modern C++ dependency in a similar way as the ICU dependency.

- Download the dependency directly from the GitHub releases section without using `git` commands. At first, we set the version used to 3.10.2.
- Cache the dependency so that it can be re-used for later builds.
- Update the autoupdater so that a pull request is automatically created when a new version of the dependency is released.

@JosDenysGitHub If this sounds good to you, I'll get started on this issue.

**Comment by JosDenysGitHub** [comment]
@isc-adang
Sure,

I'm a beginner on these wonderfull CD/CI workflows,
it'll be great to learn how to do things more efficiently !

Thanks,
Jos.
