### ISSUE TITLE
Update iKnowXML.xsl for generic attributes

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#217]
The style sheet language_development\iKnowXML.xsl cannot visualize UDGeneric1, UDGeneric2 and UDGeneric3 (markers + expansion) yet. Can you update it, please?

**Comment by JosDenysGitHub** [comment]
New styles for generic1, generic2 and generic 3
Following RGB coloring: Red=1, Green=2, Blue=3.

![image](https://user-images.githubusercontent.com/60105428/156780403-f27d3f7b-0fd1-4d8e-a271-60ce3f98d9a3.png)

**Comment by ISC-SDE** [comment]
I tested this for en_udct_test.txt with the new script genXML_with_udct.py, and can confirm that it works. Thank you!
