### ISSUE TITLE
build issue with Japanese system - warning C4819

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#22]
This issue happens when building iKnowEngineTest or iKnowALI on Japanese Windows and Japanese Visual Studio that gets installed, basically the setup that would be used by most Japanese users.

 The warning is "The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss." The warning is for the line 3153 in uchar.h: `u_isWhitespace(UChar32 c);`

The build can continue if "Treat warnings as errors" is set to No, but why this is happening needs to be investigated.

**Comment by makorin0315** [comment]
I've done some research on the Internet. (Obviously, Japanese users run into this most often!) 

To workaround this problem, if the file uchar.h is saved with "UTF-8 (With Signature), the warning disappears. So apparently the file was originally UTF-8 without BOM.

**Comment by JosDenysGitHub** [comment]
Since this is solved, and Japanese is working fine, I will cloce issue #22.
