### ISSUE TITLE
Entity Vector values need to be availble from Python interface for Japanese text

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#24]
When I run the test Python interface program, I get the following with Japanese text, i.e., Proximity & Path are empty, which is not the case with English text. Entity Vector (Path for Japnese) is probably the most important part of output for Japanese, so please make it available.

*****
(base) C:\Users\mohira\Documents>python test.py
Languages Set:
{'cs', 'sv', 'ru', 'ja', 'nl', 'de', 'fr', 'pt', 'uk', 'es', 'en'}

Input text:
これはiKnowエンジンへのPythonインターフェースです。

Index:
{'proximity': [],
 'sentences': [{'entities': [{'dominance_value': 0.0,
                              'entity_id': 0,
                              'index': 'これ',
                              'offset_start': 0,
                              'offset_stop': 2,
                              'type': 'NonRelevant'},
                             {'dominance_value': 0.0,
                              'entity_id': 0,
                              'index': 'は',
                              'offset_start': 2,
                              'offset_stop': 3,
                              'type': 'NonRelevant'},
                             {'dominance_value': 9.223372036854776e+18,
                              'entity_id': 1,
                              'index': 'iknowエンジン',
                              'offset_start': 3,
                              'offset_stop': 12,
                              'type': 'Concept'},
                             {'dominance_value': 0.0,
                              'entity_id': 2,
                              'index': 'へ',
                              'offset_start': 12,
                              'offset_stop': 13,
                              'type': 'Relation'},
                             {'dominance_value': 0.0,
                              'entity_id': 0,
                              'index': 'の',
                              'offset_start': 13,
                              'offset_stop': 14,
                              'type': 'NonRelevant'},
                             {'dominance_value': 9.223372036854776e+18,
                              'entity_id': 3,
                              'index': 'pythonインターフェース',
                              'offset_start': 14,
                              'offset_stop': 28,
                              'type': 'Concept'},
                             {'dominance_value': 0.0,
                              'entity_id': 4,
                              'index': 'です',
                              'offset_start': 28,
                              'offset_stop': 30,
                              'type': 'Relation'},
                             {'dominance_value': 0.0,
                              'entity_id': 0,
                              'index': '。',
                              'offset_start': 30,
                              'offset_stop': 31,
                              'type': 'NonRelevant'}],
                'path': [],
                'path_attributes': [],
                'sent_attributes': []}]}

**Comment by bdeboe** [comment]
per a quick test, the IRIS-embedded version still emits paths for this sentence, so also worth for @adang1345 to take a look. @JosDenysGitHub will have a better view on relevant changes since the last IRIS-embedded version that may be involved (knowing the Python interface is very much a passthrough)

**Comment by adang1345** [comment]
Running the same test in C++ also indicates that the proximity and path are empty.

**Comment by makorin0315** [comment]
Just a thought - does this have anything with what I reported to Benjamin about the current Domain Explorer (Knowledge Portal) not showing correct EV values in the Entity Vector tab?

**Comment by bdeboe** [comment]
likely. the IRIS kit I tested (where things still seemed to be working fine) was 2 months old already, it turns out.
@JosDenysGitHub ?

**Comment by JosDenysGitHub** [comment]
This has been fixed, I showed Masako how to retrieve Entity Vectors using the Python interface.
