### ISSUE TITLE
genRAW script:  normalized lowercase alphabet characters are emitted for Entity Vectors

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#27]
For alphabet characters within the Entity Vector, the genRAW python script currently uses normalized lowercase single-width characters, even if the original text uses uppercase or double-width alphabet. The expectation is to get the literal values, i.e., identical to the original text.

**Comment by bdeboe** [comment]
I believe this has always been the case. EVs, like paths, are a collection of entities, not literals, and therefore always normalized. 
If you prefer literals, you can surely edit the Python script yourself or make one dedicated to Japanese processing in order not to upset other language's expectations.

cf https://github.com/intersystems/iknow/blob/b0dea12dca435de0461b947789c3b38638326bee/language_development/genRAW.py#L150

**Comment by makorin0315** [comment]
No, in the IRIS version of genRAW, EVs used literals, not normalized versions. I've attempted to change the script myself, but I needed information from Jos on where to pick up the Literals from. He said he'll take a look, thus I assigned it to him.

**Comment by JosDenysGitHub** [comment]
I made the necessary changes to the genRAW.py script, now the literals are use as Entity Vectors.
