### ISSUE TITLE
Missing characters in output for 'Sentence_found' (part of engine.m_traces in genTrace.py)

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#28]
Although this issue is about a Python script, it actually concerns something that needs to be changed in the engine.

Where PreprocessToken introduces a space within a token (thus creating 2 tokens), the last character of the first part is replaced by space in Sentence_found, e.g. PreprocessToken "It's" -> "It 's", Sentence_found "I 's".

**Comment by JosDenysGitHub** [comment]
This problem also appeared in the IRIS version, fixed now, see Issue#28
