### ISSUE TITLE
Enhancement request: enable user dictionary

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#29]
In IRIS, it is possible to influence sentence detection and attribute detection (a.o. negation and sentiment) through a user dictionary. It would be helpful to have that functionality in the Python interface too.

**Comment by bdeboe** [comment]
I think Jos' latest round of commits added full UD functionality, so this should be ready for closing. 
Of course happy to see further suggestions to improve the UX (e.g. Python-side #48 )
