### ISSUE TITLE
Japanese: 'MissingEntityVector' warning should be included in Trace

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#30]
When iKnow processes Japanese text, it's possible that a Concept doesn't get any EntityVector attribute such as Subject, Object, Topic, OtherEntity, and DateTime (which all include EVValue). In such case, iKnow assigns the lowest priority EV value so that the entity gets included in the Entity Vector. 

For example:

吊（つ）り戸棚からはだし類が次々と15袋以上出てくる。

Since the Furigana（つ）interferes with grammatical interpretation of the sentence, the character 吊 cannot receive any EV attribute, thus receiving the lowest EV priority. 

This happens mostly when the sentence's format is unconventional, like in this example, but it's possible that a new rule that doesn't take EVs into consideration causes a similar situation.

In the IRIS version of genTrace, the generated trace includes a line like below to indicate which entity of which sentence within the input file was a Concept without EV attribute:

*** MissingEntityVector !Lexrep("吊")=JPVerbOther

However, when genTrace.py script gets run against a file that includes such sentence, "MissingEntityVector" appears after the input file name in the Command Prompt but there is no further information. The generated trace log file doesn't include any additional information about "MissingEntityVector" either. This is a problem, since it will not be possible to identify which entity/sentence is generating such warning.

**Comment by bdeboe** [comment]
Just for my understanding: you're asking for proper passing of the warning message here when using the Python API, correct? Are there any other such warning messages that suffer from the same issue?
Could this be related to the difference between `print()` and `write_ln()` in genTrace.py (very last leg of the if/elif/... clause)?

**Comment by JosDenysGitHub** [comment]
2 special Japanese linguistic trace codes, "MissingEntityVector" and "InvalidEntityVector" were not "catched" in the genTrace.py script, and thus were written to output, instead of written to file.
Fixed.

**Comment by makorin0315** [comment]
Confirmed that the trace log includes the MissingEntityVector & InvalidEntityVector information. Thanks, @JosDenysGitHub !!
