### ISSUE TITLE
Japanese: request ability to switch off (or to modify) Furigana detection

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#31]
NOTE: this is a request that came from Dr. Torikai & Dr. Noguchi @ Gunma University Hospital.

###  BACKGROUND 

For Japanese text, we've implemented automatic detection of Furigana. The specifications are as follows:

- Consider the content of a set of parentheses （） or () NonRelevant, if the text consist of All Hiragana, All Katakana or All Numbers.  
- This setting (NonRelevant) is to be true, even if the word itself or part of it is labeled Concept or Relation in the lexreps.
- This only applies to （） or () - i.e., it is NOT applicable to other types of brackets.

For example:
- 将棋の高校生プロ、藤井聡太棋聖（18）がまたしても金字塔を打ち立てた。 => All Numbers, in this example to indicate the person's age.
- 黎智英（ジミー・ライ）氏や民主活動家の周庭（アグネス・チョウ）氏が逮捕された。 => All Katakana, to indicate pronunciation of the previously mentioned proper nouns (often of Chinese/Korean origin) in Kanji.
- 北海道・阿寒（あかん）湖温泉で自然体験ツアーに出かけた。 => All Hiragana, to indicate pronunciation of the previously mentioned proper noun in Kanji.

This implementation works well in most cases, as such text is just another way of describing (or supplementary information for) the Concept that immediately precedes the set of parentheses. If the text inside the parentheses contains multiple types of characters or consists of all alphabetic characters, the implementation does not apply, as likely the information is more than just a repeat of the preceding Concept.

When the specification was originally designed back in 2013, there was a request to make this feature a switch that could be turned off, but we have no such switch as of date.

### WHAT WE WOULD LIKE TO EXPERIMENT

In the machine learning experiment Dr. Noguchi is conducting, he often comes across names of medications in the form: GENERIC_NAME (PRODUCT_NAME), i.g.,グリメピリド（アマリール）
Since most medication names are written in Katakana, the product name is almost always indexed as NonRelevant.

In iKnow sense, making アマリール in above example NonRelevant may not be a problem, since it is essentially repeating グリメピリド. In fact, considering アマリール to be a separate Concept may give more weight to the medication names than we need. 

However, Dr. Noguchi is wondering if his model can give better results if the Furigana text is tweaked. There are a couple of different ways he wants to experiment:

1. Consider the content of the parentheses to be a separate entity, i.e., グリメピリド（アマリール）would yield 2 Concepts. 
2. Consider the whole text グリメピリド（アマリール）to be one single Concept. 

Either way would have impact on the Entity Vector, proximity and dominance, but his experiment may not use them.

Currently, the Furigana implementation is outside of the language model CSV files, i.e., the iKnow engine does the work. We need Jos's help to enable ability to 1) switch off the Furigana implementation if chosen by the user; and to 2) make changes to the Furigana implementation (if chosen by the user) so that it still applies to certain types of characters but not all of the default ones.

**Comment by makorin0315** [comment]
### Experiment
With the on/off switch implemented by @JosDenysGitHub in September, it is now possible to turn Furigana implementation on & off, which is a good start for this issue. However, parentheses containing each type of characters (i.e., Katakana-only, Number-only, Hiragana-only, mixed) seem to require different approaches. To experiment for discussion purpose, I have created different branches by commenting out specific lines in IkStringAlg.h  to compare the output:

1a. Furigana ON, disable Katakana only
1b. Furigana ON, disable Katakana only - add rule to concatenate the parentheses with the preceding Concept.
2a. Furigana ON, disable Number only
2b. Furigana ON, disable Number only - add rule to concatenate the parentheses with the preceding Concept.
3a. Furigana ON, disable Hiragana only

The table below is a summary of the experiment results.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Character&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 2 entities (a) | Concatenate with preceding Concept to form 1 entity (b) | Comment
--| -- | -- | --
**Katakana** only:   <li>Furigana</li><li>Alternative&nbsp;expression</li><li>Detail of preceding Concept</li> | 〇 | ◎ | <li>Katakana   text tends to be a word unit, so it can exist as either 1 or 2 entities.</li>  <li>Grammatical   analysis is more possible as 1 entity.</li>
**Number** only:   <li>Person’s&nbsp;age&nbsp;(90%+)</li><li>Test Result</li><li>Numbered text</li> | △ | Person’s age ◎ <br/>Test Result ◎   <br/>Numbered text △ |<li>As in Katakana   case, grammatical analysis is easier for Age & Test Result when treating   as 1 entity.   </li><li>For   numbered text, approach 2b doesn’t make sense, since the number is totally unrelated   to the preceding text. However, this is a rare usage – more than 90% of   number-only parentheses content occurrences in our test corpus was person’s  age. </li>
**Hiragana** only:   <li>Furigana (90%+)</li><li>Detail of preceding Concept</li> | △ | × | <li>Unlike   Katakana, Hiragana does not always exist as a word unit, so it is difficult   to analyze the text.</li><li>It is  very rare that the detail of preceding Concept is expressed in all Hiragana,   but there are cases in medical text.</li>
**Mixed** |[current state] △ | × | <li>When the   parentheses content comprises of mixed types of characters, it can be more   than 1 entity.</li>

### Discussion Summary
On November 3rd, 2020 EST (November 4th, 2020 JST), the experiment results along with example sentences were shared with Gunma University's Dr. Torikai & Dr. Noguchi (@Rei-hub). We agreed on the following:

1. For "Katakana only" and "Number only" cases, the most desirable output (in general, in addition Medical context) is to concatenate the parentheses along with their content to the  preceding Concept, as more information is kept as a single entity. This new design would be useful in IRIS NLP as the default setting, as well for standalone iKnow.
2. For "Hiragana only", more experiment is needed: in particular, it may be helpful if we concatenate the parentheses and their content to the preceding Concept if the content is 5 or 6 characters or less, or if the content in its entirety is determined a Concept. This request was especially raised because there are some expressions that doctors may use in their notes that can/may be written in all Hiragana (i.g., しびれ, ものもらい, etc.)

### Action items
1. Language model development workload for the first item (Katakana & Number) is quite minimal. I do need to consult with @JosDenysGitHub and @bdeboe regarding how to go about making the new default settings - for my experiment purpose, I made modifications (commenting out lines for characters that I do not want Furigana) to the file IkStringAlg.h, but I'm wondering if we should implement the ability to select which character-type to enable Furigana for in the metadata file. 
2. Although "Hiragana only" experiment would be quite worthwhile, the linguistic work involved for such experiment is quite large compared to Katakana- & Number-only, due to the nature of how Hiragana characters are used. It has been agreed to put the task on the back burner for the time-being.

**Comment by JosDenysGitHub** [comment]
As of version 1.0.2 the situation regarding Furigana reading aid handling has been modified : 
- we keep the metadata switch : ([metadata.csv](https://github.com/intersystems/iknow/blob/master/language_models/ja/metadata.csv)) : "FuriganaHandling;on", if changed to "off" Furigana handling is disabled.
- if enabled, it will work as before, except for 2 cases, if all Furigana characters are Katakana or Numbers, they will no longer be treated as special (Furigana in between parenthesis is isolated and labelled NonRelevant).

**Comment by makorin0315** [comment]
For the current release of standalone iKnow and IRIS NLP 2021.1, the following has been implemented as the default for Japanese:
- If content of a pair of parentheses is either all-Number or all-Katakana AND the parentheses pair follows a Concept, the entire phrase becomes a Concept
- If content of a pair of parentheses is either all-Number or all-Katakana but the entity preceding the parentheses is not a Concept, the content of the parentheses stands as a Concept by itself
- Furigana setting (i.e., parentheses content becoming NonRelevant) is still valid for all-Hiragana content.

A separate issue will be created for an additional experiment surrounding all-Hiragana parentheses content, as discussed with Gunma University Hospital.
