### ISSUE TITLE
Python interface: 'level' for Certainty is missing

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#37]
The Certainty attribute in the English language model has a marker, span and level. When using the m_index property in the Python interface, the marker can be found through ['sent_attributes'], the span through ['path_attributes']. The level, currently either 0 (uncertain) or 9 (certain), should be in ['sent_attributes'] too, but it is missing.
Example:
Input = "This might be a problem."
['sent_attributes'] = [{'type': 'Certainty', 'offset_start': 7, 'offset_stop': 12, 'marker': 'might', 'value': '', 'unit': '', 'value2': '', 'unit2': '', 'entity_ref': 1}]

**Comment by JosDenysGitHub** [comment]
Version 1.0.3 solves this Issue.
