### ISSUE TITLE
iKnow indexing: .^SEnd|SEnd is not processed correctly

### ISSUE THREAD

**Issue by ISC-NLeclercq** [intersystems/iknow#38]
Rules containing the pattern ".^SEnd|SEnd" do not fire on that pattern.

Example:
Rule
2363;65;SBegin|ENCertBegin|","|ENPBegin+ENCertStop|.^ENPBegin+^SEnd|ENPBegin:SEnd;*|*|*|-ENCertStop|*|+ENCertStop;;

Input
Clearly, regional measurements can provide more detailed information about morphologic changes.
-> Actual pattern = ".^ENPBegin+^SEnd|SEnd" -> rule doesn't fire

Input
Clearly, regional measurements can provide more detailed information about morphologic changes that cannot be gained by globally averaged evaluations alone.
-> Actual pattern = ".^ENPBegin+^SEnd|ENPBegin" -> rule does fire

The second example shows that the rule is applicable for this input.

**Comment by JosDenysGitHub** [comment]
There was a problem with the Phases for SBegin/SEnd labels, they were not detected correctly, in this rule, SEnd did not have phase 65, and as such, was not detected. That is why the rule did not fire !
I fixed the language compiler to correctly detect the Phases, and recompiled all languages, This "case" has been added to the unit test collection of the test program, it now passes succesfully !
