### ISSUE TITLE
iKnow indexing in genRAW: Time/Frequency/Duration attribute not shown if Measurement attribute in same Concept

### ISSUE THREAD

**Issue by ISC-NLeclercq** [intersystems/iknow#39]
The Frequency attribute for 'daily' is missing in the RAW output for the following example:
input:
60 mg daily
-> attributes: attr type="measurement" literal="60 mg daily" token="60 mg" value="60" unit="mg"

The Frequency attribute is however present in the genTrace output:
input:
60 mg daily
-> index="daily" labels="ENCon;ENFrequency(a:Entity,Frequency,);ENInMeasspan;

When the token with Measurement attribute is removed, 'daily' does get the Frequency attribute in the RAW output:
input:
daily
-> attr type="frequency" literal="daily." token="daily."

**Comment by ISC-NLeclercq** [comment]
I updated the title of this issue, including Time and Duration attributes. When a Measurement attribute is present in a Concept, the Time/Frequency/Duration attribute are not shown in the RAW output, but they are shown in the Trace output.

Remark: The combination of Negation, Sentiment and Time attributes doesn't cause a problem.
input:
no good future results 

-> 
<attr type="negation" literal="no good future results" token="no">
<attr type="time" literal="no good future results" token="future">
<attr type="sentpositive" literal="no good future results" token="good">

**Comment by ISC-NLeclercq** [comment]
Correction of previous comment:
input:
no good future results

->
\<attr type="negation" literal="no good future patients" token="no"\>
\<attr type="time" literal="no good future patients" token="future"\>
\<attr type="sentpositive" literal="no good future patients" token="good"\>

**Comment by JosDenysGitHub** [comment]
Version 1.0.4 also fixes this Issue#39, @ISC-NLeclercq can you test and confirm that this is working ?
And then close the Issue :-)

**Comment by ISC-SDE** [comment]
Yes, it works. Thank you!
