### ISSUE TITLE
iKnow indexing in genRAW: space is added in preprocessor items

### ISSUE THREAD

**Issue by ISC-NLeclercq** [intersystems/iknow#40]
Preprocessor items such as "he's", 'we're", etc. are split in the preprocessor to be able to process "he" and "we" differently from "'s" and "'re". This space between "he" and "'s" and "we" and "'re" shouldn't be visible in the RAW output, but it currently is.
input:
despite what we're hearing

current output:
despite what  <we> 're hearing

desired output:
despite what  <we>'re hearing

**Comment by ISC-NLeclercq** [comment]
Correction of previous comment:
current output:
despite what \<we\> 're hearing

desired output:
despite what \<we\>'re hearing

**Comment by bdeboe** [comment]
Assuming you are talking about the `OldStyle` output, you'll probably want to put an additional condition before this line: https://github.com/intersystems/iknow/blob/817a2b6c9568dd6f4ce2618aafdddc25a4f0e1ba/language_development/genRAW.py#L113

**Comment by ISC-SDE** [comment]
Solved with an update of genRAW.py.
