### ISSUE TITLE
iKnow indexing in genRAW: only one Measurement value and unit shown when more than one value and unit in same Concept

### ISSUE THREAD

**Issue by ISC-NLeclercq** [intersystems/iknow#41]
If more than one value and unit are present in the same Concept only one value and one unit are shown in the RAW output. In the following example only '7 ounces' gets an attribute, and '7 pounds' doesn't.

input:
The baby weighs 7 pounds 7 ounces.

current output:
\<attr type="measurement" literal="7 pounds 7 ounces." token="7 pounds 7 ounces." value="7" unit="ounces"\>

desired output:
\<attr type="measurement" literal="7 pounds 7 ounces." token="7 pounds 7 ounces." value="7" unit="pounds" value2="7" unit2="ounces"\>

**Comment by JosDenysGitHub** [comment]
Version 1.0.4 solves this problem.

**Comment by JosDenysGitHub** [comment]
If @ISC-NLeclercq can verify, and close the Issue, the list will become a little smaller again :-)

**Comment by ISC-SDE** [comment]
Both values appear in the output now. Thank you!
