### ISSUE TITLE
Python interface: collect markers of the same type per entity

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#42]
When an entity contains more than one marker of the same type, e.g. two Negation markers or two DateTime markers, the m_index property in the Python interface outputs them as two separate items. It would be better to collect them into one item.

Example 1: Il n'y avaient jamais des chiens.
concerned entity: n'y avaient pas
attribute output:
[{'type': 'Negation', 'offset_start': 5, 'offset_stop': 8, 'marker': "n'y", 'value': '', 'unit': '', 'value2': '', 'unit2': '', 'entity_ref': 1}, 
{'type': 'Negation', 'offset_start': 17, 'offset_stop': 23, 'marker': 'jamais', 'value': '', 'unit': '', 'value2': '', 'unit2': '', 'entity_ref': 1}]

Example 2: These reports are for the 1997-1998 academic year.
concerned entity: 1997-1998 academic year
attribute output:
[{'type': 'DateTime', 'offset_start': 28, 'offset_stop': 37, 'marker': '1997-1998', 'value': '', 'unit': '', 'value2': '', 'unit2': '', 'entity_ref': 4}, {'type': 'DateTime', 'offset_start': 47, 'offset_stop': 52, 'marker': 'year.', 'value': '', 'unit': '', 'value2': '', 'unit2': '', 'entity_ref': 4}]

**Comment by bdeboe** [comment]
That would still ask for separate sub-entries to accommodate the different start/end positions for these tagged markers. Is there a particular use case for which this would be more convenient (worth changing the output structure)?

FWIW: for the first example, the path attribute `{'type': 'Negation', 'pos': 0, 'span': 3}` also implies how they are part of the same attributed segment.

**Comment by ISC-SDE** [comment]
This issue should have been closed already: it was solved in November 2020.
