### ISSUE TITLE
Enhancement request: move and rename compiler_report.log

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#44]
Current situation: compiler_report.log is generated in the release/bin directory when lang_update.ban is run. It overwrites the existing compiler_report.log, even if it contains data from another language model.

Request: rename the file to xx_compiler_report.log where xx represents the language code of the concerned model + put it in the language_development folder, where it is needed for genTrace.py.

**Comment by JosDenysGitHub** [comment]
This is implemented, the new logfile is named <lang>_compiler_report.log, and is written in the language_development directory, I also added some text style enhancements, and protection in case of file write failure.

**Comment by JosDenysGitHub** [comment]
After "pulling" the update, the "iKnowLanguageCompiler" must be rebuild before use !

![image](https://user-images.githubusercontent.com/60105428/96852192-21fff700-1459-11eb-8ba2-9118839391d7.png)

**Comment by JosDenysGitHub** [comment]
I did type "&lt;lang&gt;_compiler_report.log", but this is HTML of course, it's not displayed in the comment, so the 2letter language code is used to precede the report : "en_compiler_report.log" for English, "fr_compiler_report.log" for French, you get the idea :-)
