### ISSUE TITLE
Rules with SEnd and optional elements don't fire if the input is more than 1 element shorter than the pattern

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#70]
Example 1: rule 2158 in the English language model
2158;50;typeRelation|.ENArtPosspron|*typeConcept+^ENList|ENComma|.ENArtPosspron|*typeConcept+^ENNegation|ENAndOrBut+^"but"|.ENArtPosspron|*typeConcept+^ENNegation|ENColon:SEnd;*|+ENList|+ENList|+ENList|+ENList|+ENList|-ENNegStop+ENList|+ENList|+ENList|*;;

This rule has 10 elements (9 + SEnd), 3 of which are optional.
The rule fires for
"of sneezing, a sore throat and fatigue." -> 9 elements (8 + SEnd)
but not for:
"of sneezing, a headache and fatigue." -> 8 elements (7 + SEnd)

Example 2: rule 2377 in the English language model
2377;65;ENCertainty|.ENNegation|ENPBegin+ENCertStop+^ENConj|.^ENPBegin+^SEnd|ENPBegin:SEnd;*|*|-ENCertStop|*|+ENCertStop;;

This rules has 5 elements, 2 of which are optional.
The rule fires for
"perhaps what else" -> 4 elements (3 + SEnd)
but not for:
"perhaps what" -> 3 elements (2 + SEnd)

For more concerned rules and examples, please contact me directly.

**Comment by JosDenysGitHub** [comment]
Fix is in, see version 1.0.10

**Comment by ISC-SDE** [comment]
The issue is solved (checked with genTrace.py). Thanks you!
