### ISSUE TITLE
Request for language model development: emit a warning if phase of rule and label don't match

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#78]
Rules are organized in "phases". The label definitions contain a list of phases in which the label can be used. 
If a label is used in a rule in a phase for which it is not defined, the rule won't fire, because the input pattern is not found. Can you let the engine emit a warning about the mismatch in phases?

**Comment by JosDenysGitHub** [comment]
Sure, this used to be the case in the Delve tools, I guess ?
I'll add it...

**Comment by JosDenysGitHub** [comment]
I have added this request (https://github.com/intersystems/iknow/commit/cab117ac97b65e319c50f6a791bd0a51efab180e), if a label is used in a rule and the phases don't match, an error is thrown and the rule input pattern is presented.

**Comment by ISC-SDE** [comment]
Strangely, lang_update fr ran without any errors and picked up the new rule with mismatch in phases when it ran the first time, although it detected the new rule and gave it a number. However, after removing the rule and introducing it again, lang_update did return an error message and stopped. Maybe it didn't work the first time because it was the first run in a new branch? 
I assume I can close the issue.
