### ISSUE TITLE
 Request for language model development: emit a warning if unknown labels are used in lexreps.csv

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#81]
If an undefined label is used in lexreps.csv, the build of the language compiler fails with this error:
57>C:\iKnow_GH\modules\aho\inl\de\lexrep\MatchObjs.inl(1,22): error C2466: cannot allocate an array of constant siz
       e 0 [C:\iKnow_GH\modules\aho\model0_de.vcxproj]

It would be more convenient to get a warning like "undefined label DEVerbadj in lexreps.csv, line 32424".

**Comment by JosDenysGitHub** [comment]
This is fixed (https://github.com/intersystems/iknow/commit/d471ffb9ae652093ab52e7517b03d42e82789fef),
The language compilation will be halted and an error message will be displayed, listing the lexrep and the invalid label.
Beware : This is a change in the language compiler, don't forget to rebuild the iKnowLanguageCompiler module (best is to rebuild the solution each time you synchronize with the main hub).

**Comment by ISC-SDE** [comment]
I can confirm that this is fixed. Thanks.
